# -*- coding: utf-8 -*-

from PyQt5 import QtCore, QtGui, QtWidgets
from Modules.ImageBinarizationMethods import binaryMethods

class Ui_SkeletonitationWindow(QtWidgets.QWidget):
    binarizationMethodChangedSignal = QtCore.pyqtSignal(int)
    thresholdValueChangedSignal = QtCore.pyqtSignal(int)
    binaryThresholdValueSpinBoxSignal = QtCore.pyqtSignal(int)
    gaussianCSpinBoxSignal = QtCore.pyqtSignal(float)
    gaussianCValueSliderSignal = QtCore.pyqtSignal(float)
    gaussianBlockSizeSpinBoxSignal = QtCore.pyqtSignal(int)
    gaussianBlockSizeValueSliderSignal = QtCore.pyqtSignal(int)
    binarizationMethodsList = [""] + binaryMethods

    def setupUi(self, SkeletonitationWindow):
        SkeletonitationWindow.setObjectName("SkeletonitationWindow")
        SkeletonitationWindow.resize(441, 496)
        self.layoutWidget = QtWidgets.QWidget(SkeletonitationWindow)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 50, 421, 33))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.binarizationMethodsLabel = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.binarizationMethodsLabel.setFont(font)
        self.binarizationMethodsLabel.setObjectName("binarizationMethodsLabel")
        self.horizontalLayout.addWidget(self.binarizationMethodsLabel)
        self.binarizationMethodsComboBox = QtWidgets.QComboBox(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.binarizationMethodsComboBox.sizePolicy().hasHeightForWidth())
        self.binarizationMethodsComboBox.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.binarizationMethodsComboBox.setFont(font)
        self.binarizationMethodsComboBox.setObjectName("binarizationMethodsComboBox")
        self.horizontalLayout.addWidget(self.binarizationMethodsComboBox)
        self.binaryThresholdGroupBox = QtWidgets.QGroupBox(SkeletonitationWindow)
        self.binaryThresholdGroupBox.setEnabled(False)
        self.binaryThresholdGroupBox.setGeometry(QtCore.QRect(10, 100, 421, 121))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.binaryThresholdGroupBox.setFont(font)
        self.binaryThresholdGroupBox.setObjectName("binaryThresholdGroupBox")
        self.layoutWidget1 = QtWidgets.QWidget(self.binaryThresholdGroupBox)
        self.layoutWidget1.setGeometry(QtCore.QRect(0, 20, 421, 97))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget1)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.thresholdValueLabel = QtWidgets.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.thresholdValueLabel.setFont(font)
        self.thresholdValueLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.thresholdValueLabel.setIndent(-1)
        self.thresholdValueLabel.setObjectName("thresholdValueLabel")
        self.horizontalLayout_3.addWidget(self.thresholdValueLabel)
        self.binaryThresholdValueSpinBox = QtWidgets.QSpinBox(self.layoutWidget1)
        self.binaryThresholdValueSpinBox.setMinimum(0)
        self.binaryThresholdValueSpinBox.setMaximum(255)
        self.binaryThresholdValueSpinBox.setObjectName("binaryThresholdValueSpinBox")
        self.horizontalLayout_3.addWidget(self.binaryThresholdValueSpinBox)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.thresholdMinValueLabel = QtWidgets.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.thresholdMinValueLabel.setFont(font)
        self.thresholdMinValueLabel.setIndent(-1)
        self.thresholdMinValueLabel.setObjectName("thresholdMinValueLabel")
        self.horizontalLayout_2.addWidget(self.thresholdMinValueLabel)
        self.thresholdValueSlider = QtWidgets.QSlider(self.layoutWidget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.thresholdValueSlider.sizePolicy().hasHeightForWidth())
        self.thresholdValueSlider.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.thresholdValueSlider.setFont(font)
        self.thresholdValueSlider.setMaximum(255)
        self.thresholdValueSlider.setProperty("value", 0)
        self.thresholdValueSlider.setOrientation(QtCore.Qt.Horizontal)
        self.thresholdValueSlider.setTickPosition(QtWidgets.QSlider.TicksBelow)
        self.thresholdValueSlider.setObjectName("thresholdValueSlider")
        self.horizontalLayout_2.addWidget(self.thresholdValueSlider)
        self.thresholdMaxValueLabel = QtWidgets.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.thresholdMaxValueLabel.setFont(font)
        self.thresholdMaxValueLabel.setIndent(-1)
        self.thresholdMaxValueLabel.setObjectName("thresholdMaxValueLabel")
        self.horizontalLayout_2.addWidget(self.thresholdMaxValueLabel)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.adaptiveGaussianGroupBox = QtWidgets.QGroupBox(SkeletonitationWindow)
        self.adaptiveGaussianGroupBox.setEnabled(False)
        self.adaptiveGaussianGroupBox.setGeometry(QtCore.QRect(10, 250, 421, 181))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.adaptiveGaussianGroupBox.setFont(font)
        self.adaptiveGaussianGroupBox.setObjectName("adaptiveGaussianGroupBox")
        self.widget = QtWidgets.QWidget(self.adaptiveGaussianGroupBox)
        self.widget.setGeometry(QtCore.QRect(0, 20, 421, 155))
        self.widget.setObjectName("widget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.horizontalLayout_4.addWidget(self.label)
        self.gaussianBlockSizeSpinBox = QtWidgets.QSpinBox(self.widget)
        self.gaussianBlockSizeSpinBox.setFrame(True)
        self.gaussianBlockSizeSpinBox.setButtonSymbols(QtWidgets.QAbstractSpinBox.UpDownArrows)
        self.gaussianBlockSizeSpinBox.setMinimum(3)
        self.gaussianBlockSizeSpinBox.setMaximum(255)
        self.gaussianBlockSizeSpinBox.setObjectName("gaussianBlockSizeSpinBox")
        self.horizontalLayout_4.addWidget(self.gaussianBlockSizeSpinBox)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)
        self.line = QtWidgets.QFrame(self.widget)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout_2.addWidget(self.line)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.gaussianBlockSizeMinValueLabel = QtWidgets.QLabel(self.widget)
        self.gaussianBlockSizeMinValueLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.gaussianBlockSizeMinValueLabel.setObjectName("gaussianBlockSizeMinValueLabel")
        self.horizontalLayout_6.addWidget(self.gaussianBlockSizeMinValueLabel)
        self.gaussianBlockSizeValueSlider = QtWidgets.QSlider(self.widget)
        self.gaussianBlockSizeValueSlider.setMinimum(3)
        self.gaussianBlockSizeValueSlider.setMaximum(255)
        self.gaussianBlockSizeValueSlider.setOrientation(QtCore.Qt.Horizontal)
        self.gaussianBlockSizeValueSlider.setTickPosition(QtWidgets.QSlider.TicksBelow)
        self.gaussianBlockSizeValueSlider.setObjectName("gaussianBlockSizeValueSlider")
        self.horizontalLayout_6.addWidget(self.gaussianBlockSizeValueSlider)
        self.gaussianBlockSizeMaxValueLabel = QtWidgets.QLabel(self.widget)
        self.gaussianBlockSizeMaxValueLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.gaussianBlockSizeMaxValueLabel.setObjectName("gaussianBlockSizeMaxValueLabel")
        self.horizontalLayout_6.addWidget(self.gaussianBlockSizeMaxValueLabel)
        self.verticalLayout_2.addLayout(self.horizontalLayout_6)
        self.line_2 = QtWidgets.QFrame(self.widget)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.verticalLayout_2.addWidget(self.line_2)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_2 = QtWidgets.QLabel(self.widget)
        self.label_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_5.addWidget(self.label_2)
        self.gaussianCSpinBox = QtWidgets.QSpinBox(self.widget)
        self.gaussianCSpinBox.setMinimum(-30)
        self.gaussianCSpinBox.setMaximum(30)
        self.gaussianCSpinBox.setObjectName("gaussianCSpinBox")
        self.horizontalLayout_5.addWidget(self.gaussianCSpinBox)
        self.verticalLayout_2.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.gaussianCMinValueLabel = QtWidgets.QLabel(self.widget)
        self.gaussianCMinValueLabel.setAlignment(QtCore.Qt.AlignJustify|QtCore.Qt.AlignVCenter)
        self.gaussianCMinValueLabel.setObjectName("gaussianCMinValueLabel")
        self.horizontalLayout_7.addWidget(self.gaussianCMinValueLabel)
        self.gaussianCValueSlider = QtWidgets.QSlider(self.widget)
        self.gaussianCValueSlider.setMinimum(-30)
        self.gaussianCValueSlider.setMaximum(30)
        self.gaussianCValueSlider.setOrientation(QtCore.Qt.Horizontal)
        self.gaussianCValueSlider.setTickPosition(QtWidgets.QSlider.TicksBelow)
        self.gaussianCValueSlider.setObjectName("gaussianCValueSlider")
        self.horizontalLayout_7.addWidget(self.gaussianCValueSlider)
        self.gaussianCMaxValueLabel = QtWidgets.QLabel(self.widget)
        self.gaussianCMaxValueLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.gaussianCMaxValueLabel.setObjectName("gaussianCMaxValueLabel")
        self.horizontalLayout_7.addWidget(self.gaussianCMaxValueLabel)
        self.verticalLayout_2.addLayout(self.horizontalLayout_7)
        self.widget = QtWidgets.QWidget(SkeletonitationWindow)
        self.widget.setGeometry(QtCore.QRect(10, 10, 263, 23))
        self.widget.setObjectName("widget")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")

        self.retranslateUi(SkeletonitationWindow)
        # Enables
        self.binaryThresholdGroupBox.setEnabled(False)
        self.adaptiveGaussianGroupBox.setEnabled(False)
        # Triggers
        self.binarizationMethodsComboBox.addItems(self.binarizationMethodsList)
        self.binarizationMethodsComboBox.activated[str].connect(self.onBinarizationMethodChanged)
        self.thresholdValueSlider.valueChanged.connect(self.onThresholdSliderValueChanged)
        self.binaryThresholdValueSpinBox.valueChanged.connect(self.onThresholdSpinBoxValueChanged)
        self.gaussianBlockSizeSpinBox.valueChanged.connect(self.onGaussianBlockSizeSpinBoxChanged)
        self.gaussianBlockSizeValueSlider.valueChanged.connect(self.onGaussianBlockSizeSliderChanged)
        self.gaussianCSpinBox.valueChanged.connect(self.onGaussianCSpinBoxChanged)
        self.gaussianCValueSlider.valueChanged.connect(self.onGaussianCSliderChanged)
        QtCore.QMetaObject.connectSlotsByName(SkeletonitationWindow)

    def onGaussianCSpinBoxChanged(self, value):
        self.gaussianCValueSlider.setValue(value)
        self.gaussianCSpinBoxSignal.emit(value)

    def onGaussianCSliderChanged(self, value):
        self.gaussianCSpinBox.setValue(value)
        self.gaussianCValueSliderSignal.emit(value)

    def onGaussianBlockSizeSpinBoxChanged(self, value):
        self.gaussianBlockSizeValueSlider.setValue(value)
        self.gaussianBlockSizeSpinBoxSignal.emit(value)

    def onGaussianBlockSizeSliderChanged(self, value):
        self.gaussianBlockSizeSpinBox.setValue(value)
        self.gaussianBlockSizeValueSliderSignal.emit(value)

    def onThresholdSliderValueChanged(self, value):
        self.binaryThresholdValueSpinBox.setValue(value)
        self.thresholdValueChangedSignal.emit(value)

    def onThresholdSpinBoxValueChanged(self, value):
        self.thresholdValueSlider.setValue(value)
        self.binaryThresholdValueSpinBoxSignal.emit(value)

    def onBinarizationMethodChanged(self, method):
        methodIndex = self.binarizationMethodsList.index(method)

        setEnabled = True if methodIndex == 1 else False
        self.binaryThresholdGroupBox.setEnabled(setEnabled)

        setEnabled = True if methodIndex == 2 else False
        self.adaptiveGaussianGroupBox.setEnabled(setEnabled)

        self.binarizationMethodChangedSignal.emit(methodIndex)

    def retranslateUi(self, SkeletonitationWindow):
        _translate = QtCore.QCoreApplication.translate
        SkeletonitationWindow.setWindowTitle(_translate("SkeletonitationWindow", "Skeletonization"))
        self.binarizationMethodsLabel.setText(_translate("SkeletonitationWindow", "Binarization Method:"))
        self.binaryThresholdGroupBox.setTitle(_translate("SkeletonitationWindow", "Binary Thresholding"))
        self.thresholdValueLabel.setText(_translate("SkeletonitationWindow", "Threshold Value = "))
        self.thresholdMinValueLabel.setText(_translate("SkeletonitationWindow", "0"))
        self.thresholdMaxValueLabel.setText(_translate("SkeletonitationWindow", "255"))
        self.adaptiveGaussianGroupBox.setTitle(_translate("SkeletonitationWindow", "Adaptive Gaussian Threshold"))
        self.label.setText(_translate("SkeletonitationWindow", "Block size = "))
        self.gaussianBlockSizeMinValueLabel.setText(_translate("SkeletonitationWindow", "3"))
        self.gaussianBlockSizeMaxValueLabel.setText(_translate("SkeletonitationWindow", "255"))
        self.label_2.setText(_translate("SkeletonitationWindow", "C = "))
        self.gaussianCMinValueLabel.setText(_translate("SkeletonitationWindow", "-30"))
        self.gaussianCMaxValueLabel.setText(_translate("SkeletonitationWindow", "30"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    SkeletonitationWindow = QtWidgets.QWidget()
    ui = Ui_SkeletonitationWindow()
    ui.setupUi(SkeletonitationWindow)
    SkeletonitationWindow.show()
    sys.exit(app.exec_())
