# -*- coding: utf-8 -*-

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_SkeletonitationWindow(QtWidgets.QWidget):
    binarizationMethodChangedSignal = QtCore.pyqtSignal(str)
    thresholdValueChangedSignal = QtCore.pyqtSignal(int)

    def setupUi(self, SkeletonitationWindow):
        SkeletonitationWindow.setObjectName("SkeletonitationWindow")
        SkeletonitationWindow.resize(400, 300)
        self.widget = QtWidgets.QWidget(SkeletonitationWindow)
        self.widget.setGeometry(QtCore.QRect(10, 10, 381, 23))
        self.widget.setObjectName("widget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.binarizationMethodsLabel = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        self.binarizationMethodsLabel.setFont(font)
        self.binarizationMethodsLabel.setObjectName("binarizationMethodsLabel")
        self.horizontalLayout.addWidget(self.binarizationMethodsLabel)
        self.binarizationMethodsComboBox = QtWidgets.QComboBox(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.binarizationMethodsComboBox.sizePolicy().hasHeightForWidth())
        self.binarizationMethodsComboBox.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        self.binarizationMethodsComboBox.setFont(font)
        self.binarizationMethodsComboBox.setObjectName("binarizationMethodsComboBox")
        self.binarizationMethodsComboBox.addItems(
            [
                "Threshold Binary"
            ]
        )
        self.binarizationMethodsComboBox.activated[str].connect(self.onBinarizationMethodChanged)
        self.horizontalLayout.addWidget(self.binarizationMethodsComboBox)
        self.widget1 = QtWidgets.QWidget(SkeletonitationWindow)
        self.widget1.setGeometry(QtCore.QRect(10, 50, 381, 97))
        self.widget1.setObjectName("widget1")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget1)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.thresholdValueLabel = QtWidgets.QLabel(self.widget1)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        self.thresholdValueLabel.setFont(font)
        self.thresholdValueLabel.setObjectName("thresholdValueLabel")
        self.horizontalLayout_3.addWidget(self.thresholdValueLabel)
        self.thresholdSelectedValueLabel = QtWidgets.QLabel(self.widget1)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        self.thresholdSelectedValueLabel.setFont(font)
        self.thresholdSelectedValueLabel.setObjectName("thresholdSelectedValueLabel")
        self.horizontalLayout_3.addWidget(self.thresholdSelectedValueLabel)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.thresholdMinValueLabel = QtWidgets.QLabel(self.widget1)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(10)
        self.thresholdMinValueLabel.setFont(font)
        self.thresholdMinValueLabel.setObjectName("thresholdMinValueLabel")
        self.horizontalLayout_2.addWidget(self.thresholdMinValueLabel)
        self.thresholdValueSlider = QtWidgets.QSlider(self.widget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.thresholdValueSlider.sizePolicy().hasHeightForWidth())
        self.thresholdValueSlider.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        self.thresholdValueSlider.setFont(font)
        self.thresholdValueSlider.setMaximum(255)
        self.thresholdValueSlider.setProperty("value", 125)
        self.thresholdValueSlider.setOrientation(QtCore.Qt.Horizontal)
        self.thresholdValueSlider.setTickPosition(QtWidgets.QSlider.TicksBelow)
        self.thresholdValueSlider.setObjectName("thresholdValueSlider")
        self.thresholdValueSlider.valueChanged.connect(self.onThresholdSliderValueChanged)
        self.horizontalLayout_2.addWidget(self.thresholdValueSlider)
        self.thresholdMaxValueLabel = QtWidgets.QLabel(self.widget1)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(10)
        self.thresholdMaxValueLabel.setFont(font)
        self.thresholdMaxValueLabel.setObjectName("thresholdMaxValueLabel")
        self.horizontalLayout_2.addWidget(self.thresholdMaxValueLabel)
        self.verticalLayout.addLayout(self.horizontalLayout_2)

        self.retranslateUi(SkeletonitationWindow)
        QtCore.QMetaObject.connectSlotsByName(SkeletonitationWindow)

    def onThresholdSliderValueChanged(self):
        value = self.thresholdValueSlider.value()
        self.thresholdSelectedValueLabel.setText(str(value))

        self.thresholdValueChangedSignal.emit(value)

    def onBinarizationMethodChanged(self, method):
        self.binarizationMethodChangedSignal.emit(method)

    def retranslateUi(self, SkeletonitationWindow):
        _translate = QtCore.QCoreApplication.translate
        SkeletonitationWindow.setWindowTitle(_translate("SkeletonitationWindow", "Skeletonization"))
        self.binarizationMethodsLabel.setText(_translate("SkeletonitationWindow", "Binarization Method:"))
        self.thresholdValueLabel.setText(_translate("SkeletonitationWindow", "Threshold Value:"))
        self.thresholdSelectedValueLabel.setText(_translate("SkeletonitationWindow", "125"))
        self.thresholdMinValueLabel.setText(_translate("SkeletonitationWindow", "0"))
        self.thresholdMaxValueLabel.setText(_translate("SkeletonitationWindow", "255"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    SkeletonitationWindow = QtWidgets.QWidget()
    ui = Ui_SkeletonitationWindow()
    ui.setupUi(SkeletonitationWindow)
    SkeletonitationWindow.show()
    sys.exit(app.exec_())
